ALTER TABLE `reg_entity_farm_providers` ADD `CL_PRODUCT_TYPES_ID` INT NULL DEFAULT '1' AFTER `REG_ENTITY_SUPPLIER_ID`;
ALTER TABLE `reg_entity_farm_providers` ADD CONSTRAINT `FK_CL_PRODUCTTYPE` FOREIGN KEY (`CL_PRODUCT_TYPES_ID`) REFERENCES `cl_product_types`(`ID`) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE `reg_entity_staff_management` ADD `WORKERS_REPRESENTATIVE_GROUP` TINYINT(1) NOT NULL AFTER `SAFETY_CONDITION`;


/** PLOTS **/
ALTER TABLE `reg_entity_farmag_plots` CHANGE `ENTITY_FARM_ID` `REG_ENTITY_FARM_ID` INT(11) NOT NULL DEFAULT '0';