ALTER TABLE `dt_farmaq_pond_management`
  ADD `CL_REF_SPECIES_ID`int(11) DEFAULT NULL AFTER `FEED_LOT_NUMBER`,
  ADD CONSTRAINT `FK_DT_FARMAQ_POND_MANAGEMENT_CL_REF_SPECIES_ID`
  FOREIGN KEY (`CL_REF_SPECIES_ID`) REFERENCES `cl_ref_species`(`id`);