CREATE TABLE `sys_password_reset_tokens` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(16) CHARACTER SET utf8 NOT NULL,
  `NAME` varchar(64) CHARACTER SET utf8 NOT NULL,
  `TOKEN` varchar(512) CHARACTER SET utf8 DEFAULT NULL,
  `EXPIRY_DATE` timestamp,
  `SYS_USER_ID`  int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_SYS_PASSWORD_RESET_TOKENS_SYS_USER`
  FOREIGN KEY (`SYS_USER_ID`) REFERENCES `sys_users`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `sys_verification_tokens` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `CODE` varchar(16) CHARACTER SET utf8 NOT NULL,
  `NAME` varchar(64) CHARACTER SET utf8 NOT NULL,
  `TOKEN` varchar(512) CHARACTER SET utf8 DEFAULT NULL,
  `EXPIRY_DATE` timestamp,
  `SYS_USER_ID`  int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_SYS_VERIFICATION_TOKENS_SYS_USER`
  FOREIGN KEY (`SYS_USER_ID`) REFERENCES `sys_users`(`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

