ALTER TABLE `cl_farm_pond_activity_types`
  ADD `CL_RECOMMAND_UNIT_ID` int(11) DEFAULT NULL,
  ADD CONSTRAINT `FK_CL_FARM_POND_ACTIVITY_TYPES_RECOMMAND_UNIT_ID` FOREIGN KEY (`CL_RECOMMAND_UNIT_ID`) REFERENCES `cl_app_quantity_units` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `cl_farm_plot_activity_types`
  ADD `CL_RECOMMAND_UNIT_ID` int(11) DEFAULT NULL,
  ADD CONSTRAINT `FK_CL_FARM_PLOT_ACTIVITY_TYPES_RECOMMAND_UNIT_ID` FOREIGN KEY (`CL_RECOMMAND_UNIT_ID`) REFERENCES `cl_app_quantity_units` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;
