ALTER TABLE `cl_ref_products`
  ADD `REG_ENTITY_PRODUCT_SUPPLIER_ID`int(10) unsigned DEFAULT NULL AFTER `CL_RECOMMAND_UNIT_ID`,
  ADD CONSTRAINT `FK_CL_REF_PRODUCTS_REG_ENTITY_PRODUCT_SUPPLIER_ID`
    FOREIGN KEY (`REG_ENTITY_PRODUCT_SUPPLIER_ID`) REFERENCES `reg_entity_product_suppliers` (`ID`);

ALTER TABLE `cl_columns` ADD `REG_ENTITY_PRODUCT_SUPPLER_ID` BOOLEAN DEFAULT FALSE;

UPDATE `cl_columns` set `REG_ENTITY_PRODUCT_SUPPLER_ID` = true WHERE `TABLE_NAME` = 'cl_ref_products';