ALTER TABLE `blueverifik8`.`cl_app_administrative_characteristic_types` 
CHANGE COLUMN `CODE` `CODE` VARCHAR(16) CHARACTER SET 'utf8' NOT NULL ;
ALTER TABLE `blueverifik8`.`cl_app_administrative_characteristic_types` 
CHANGE COLUMN `DESCRIPTION` `DESCRIPTION` VARCHAR(512) CHARACTER SET 'utf8' NULL ;
ALTER TABLE `blueverifik8`.`cl_ref_product_types` 
ADD COLUMN `CL_RECOMAND_QUANTITY_UNIT_ID` INT(11) NULL COMMENT 'Recommanded unit type (volume etc) to enable filtering of proposed units' AFTER `DESCRIPTION`;
ALTER TABLE `blueverifik8`.`cl_ref_product_types` 
ADD INDEX `FK_RECOMAND_UNIT_TYPE_idx` (`CL_RECOMAND_QUANTITY_UNIT_ID` ASC);
ALTER TABLE `blueverifik8`.`cl_ref_product_types` 
ADD CONSTRAINT `FK_RECOMAND_UNIT_TYPE`
  FOREIGN KEY (`CL_RECOMAND_QUANTITY_UNIT_ID`)
  REFERENCES `blueverifik8`.`cl_app_quantity_unit_types` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  ALTER TABLE `blueverifik8`.`cl_ref_products` 
ADD COLUMN `CL_RECOMMAND_UNIT_ID` INT(11) NULL COMMENT 'The recommanded unit for this product (example: kg / litre etc...) to preload the unit in the selection' AFTER `CL_PRODUCTS_TYPE_ID`;
ALTER TABLE `blueverifik8`.`cl_ref_products` 
ADD INDEX `FK_REF_PRODUCTS_RECOMMAND_UNIT_ID_idx` (`CL_RECOMMAND_UNIT_ID` ASC);
ALTER TABLE `blueverifik8`.`cl_ref_products` 
ADD CONSTRAINT `FK_REF_PRODUCTS_RECOMMAND_UNIT_ID`
  FOREIGN KEY (`CL_RECOMMAND_UNIT_ID`)
  REFERENCES `blueverifik8`.`cl_app_quantity_units` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  CREATE TABLE `jt_plot_activity_product_types` (
  `CL_FARM_PLOT_ACTIVITY_ID` int(11) NOT NULL,
  `CL_PRODUCT_TYPE_ID` int(11) NOT NULL,
  `DESCRIPTION` varchar(512) COLLATE utf8_bin DEFAULT NULL,
  `UPDATER_ID` int(11) NOT NULL DEFAULT '1',
  `COMMENT` varchar(512) COLLATE utf8_bin DEFAULT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY `FK_PLOT_ACTIVITY_PRODUCT_TYPE_UPDATER_ID` (`UPDATER_ID`),
  KEY `FK_PLOT_ACTIVITY_TYPE_PRODUCT_TYPE_UNIK_FARM_idx` (`CL_FARM_PLOT_ACTIVITY_ID`),
  KEY `FK_PLOT_ACTIVITY_TYPE_PRODUCT_TYPE_UNIK_PRODUCT_TYPE_idx` (`CL_PRODUCT_TYPE_ID`),
  CONSTRAINT `FK_FARM_PLOT_ACTIVITY_PRODUCT_TYPE_UPDATER_ID` FOREIGN KEY (`UPDATER_ID`) REFERENCES `sys_users` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_PLOT_ACTIVITY_TYPE_PRODUCT_TYPE_UNIK_FARM` FOREIGN KEY (`CL_FARM_PLOT_ACTIVITY_ID`) REFERENCES `cl_farm_plot_activity_types` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_PLOT_ACTIVITY_TYPE_PRODUCT_TYPE_UNIK_PRODUCT_TYPE` FOREIGN KEY (`CL_PRODUCT_TYPE_ID`) REFERENCES `cl_ref_product_types` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='joint table to define the type of product for a given plot activity. If no entry, no product is needed';
CREATE TABLE `jt_pond_activity_product_types` (
  `CL_FARM_POND_ACTIVITY_ID` int(11) NOT NULL,
  `CL_PRODUCT_TYPE_ID` int(11) NOT NULL,
  `DESCRIPTION` varchar(512) COLLATE utf8_bin DEFAULT NULL,
  `UPDATER_ID` int(11) NOT NULL DEFAULT '1',
  `COMMENT` varchar(512) COLLATE utf8_bin DEFAULT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `CL_PRODUCT_TYPE_ID_UNIQUE` (`CL_PRODUCT_TYPE_ID`),
  UNIQUE KEY `CL_FARM_POND_ACTIVITY_ID_UNIQUE` (`CL_FARM_POND_ACTIVITY_ID`),
  KEY `FK_POND_ACTIVITY_PRODUCT_TYPE_UPDATER_ID` (`UPDATER_ID`),
  CONSTRAINT `FK_FARM_POND_ACTIVITY_PRODUCT_TYPE_UPDATER_ID` FOREIGN KEY (`UPDATER_ID`) REFERENCES `sys_users` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_POND_ACTIVITY_TYPE_PRODUCT_TYPE_UNIK_FARM` FOREIGN KEY (`CL_FARM_POND_ACTIVITY_ID`) REFERENCES `cl_farm_pond_activity_types` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_POND_ACTIVITY_TYPE_PRODUCT_TYPE_UNIK_PRODUCT_TYPE` FOREIGN KEY (`CL_PRODUCT_TYPE_ID`) REFERENCES `cl_ref_product_types` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='joint table to define the type of product for a given pond activity. If no entry, no product is needed';

